Added metadata field to VectorEnv and VectorWrapper. Implements #1005.
Farama-Foundation/Gymnasium pull request #1006
Opened 2024-04-10 14:46 UTC by TimSchneider42

# Description

Added metadata field to VectorEnv and VectorWrapper. 

Fixes #1005 

## Type of change

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-04-10 14:50 UTC, pseudo-rnd-thoughts approved these changes

2024-04-10 14:51 UTC, pseudo-rnd-thoughts requested changes
Thanks for the PR, could you add some tests quickly?

2024-04-10 15:10 UTC, Kallinteris-Andreas requested changes
Also please add something to the documentation About the metadata member variable

2024-04-11 09:58 UTC, pseudo-rnd-thoughts approved these changes
Thanks for the changes

2024-04-11 09:58 UTC, merged