Add width and height check for MujocoRenderer
Farama-Foundation/Gymnasium pull request #1230
Opened 2024-10-23 15:54 UTC by Beanpow

# Description

The width and height of OffScreenViewer cannot be None otherwise, it will cause the error. Adding a type check before creating the opengl_context could provide more information for debugging.

Fixes #1225

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-10-23 15:56 UTC, Beanpow commented
@Kallinteris-Andreas could you review this code?

2024-10-23 16:33 UTC, pseudo-rnd-thoughts requested changes

2024-10-23 16:33 UTC, pseudo-rnd-thoughts commented on gymnasium/envs/mujoco/mujoco_rendering.py
> +            ), "The width and height cannot be `None` when the render_mode is not Human."
Could you specify what the width and height values are to help users debug
`f'The width ({width}) and height ({height}) cannot be `None`'` ...

2024-10-24 11:38 UTC, pseudo-rnd-thoughts approved these changes

2024-10-24 12:18 UTC, Kallinteris-Andreas reviewed
will be merged after https://github.com/Farama-Foundation/Gymnasium/pull/1229

2024-10-24 16:56 UTC, Kallinteris-Andreas approved these changes
LGTM I will merge after https://github.com/Farama-Foundation/Gymnasium/pull/1229 , @Beanpow you may need to do a merge then,

2024-10-24 18:41 UTC, pseudo-rnd-thoughts commented
@Kallinteris-Andreas are you sure we can't merge now?

2024-10-25 08:33 UTC, merged