Fix discrete CarRacing-v3
Farama-Foundation/Gymnasium pull request #1253
Opened 2024-11-15 10:14 UTC by Sebastian-Griesbach

# Description

CarRacing-v3 in discrete mode first converts the action to a float value before checking if the action is part of the discrete action-space. This causes an error to be raised.

Minimal example to reproduce this error:

```
import gymnasium as gym
env = gym.make("CarRacing-v3", continuous=False)
_ = env.reset()
action = env.action_space.sample()
_ = env.step(action)
```

This problem can be fixed simply by moving the float conversion to after the `if self.continuous:` check such that for the discrete case `else:` the action will still be an integer. And the `InvalidAction` error is not raised.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [NA] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-15 15:57 UTC, pseudo-rnd-thoughts requested changes
Thanks for spotting this issue, could you add a test to check that this works, probably in `tests/envs/test_env_implementations.py`
I believe that Lunar Lander has a similar `continuous=False`, could you add this to the test. You just need to pass valid and invalid action and check that the error occurs

2024-11-17 13:29 UTC, Sebastian-Griesbach commented
I added a test that checks if continuous actions fail in the discrete setting and discrete actions don't raise any error.

2024-11-18 11:56 UTC, pseudo-rnd-thoughts approved these changes
Thanks for making that change @Sebastian-Griesbach

2024-11-18 11:56 UTC, merged

2024-12-30 21:21 UTC, Kallinteris-Andreas commented
For how long has this bug existed, do we need to list it in the environment version history

https://github.com/Farama-Foundation/Gymnasium/blob/e73245912087d47b538dcdb45fa9a9d185b805c5/gymnasium/envs/box2d/car_racing.py#L192-L196

2025-01-01 23:06 UTC, pseudo-rnd-thoughts commented
I dont think this changes environment behaviour