Add REINFORCE implementation tutorial
Farama-Foundation/Gymnasium pull request #155
Opened 2022-11-22 13:35 UTC by siddarth-c

# Description

Created a new tutorial depicting the new .step() function of gymnasium v26 using PyTorch. REINFORCE is employed to solve Mujoco's Reacher.

## Type of change

Please delete options that are not relevant.

- [ ] This change requires a documentation update

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-22 15:47 UTC, pseudo-rnd-thoughts requested changes
Thanks for the tutorial, it looks very helpful.
Could you fix the pre-commit issues and address the comments

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +df1 = pd.DataFrame(reinforce_rewards_across_seeds).melt()
Can this be replaced by the `RecordEpisodeStatistics` wrappers and matplotlib

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +        """
We use google style docstrings, could you update

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +warnings.filterwarnings("ignore")
Why have you added this?

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +class Policy_Network(nn.Module):
Could you add a description to explain what the policy network does, why this architecture, what its input and output is

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +class REINFORCE():
Could you add a description of how the `REINFORCE` algorithm works, link to the original paper, explain the purpose of the hyperparameters

2022-11-22 15:47 UTC, pseudo-rnd-thoughts commented on docs/tutorials/reinforce_reacher_gym_v26.py
> +episodes = int(5e3)
Could you explain how the training works?

2022-11-23 12:42 UTC, siddarth-c commented
I have updated the files as per the readme.md
Will do better the next time, thanks for bearing with me!

2022-11-23 14:10 UTC, pseudo-rnd-thoughts commented
No worries, currently when I build the tutorial, on the left hand side, all of the titles appear here. 
I believe it is the way that you have structured the sections that causes this. could you fix
In addition, the same issues that get reported when building still appear and the final figure doesn't appear

2022-11-24 11:31 UTC, siddarth-c commented
I have modified the structure of the titles and code following the Blackjack tutorial. And running through the tests mentioned in readme.md I do not get any warnings.

2022-11-24 13:24 UTC, pseudo-rnd-thoughts commented
@siddarth-c I have made a number of upgrades to the tutorials. There are only a couple more thing before we can merge
1. Replace the top image of the agent with a gif of the trained agent completing the environment
2. Could you add an image for the policy network should the data flow. i.e., input data -> shared network -> split to mean network and std network -> output

2022-11-25 05:13 UTC, siddarth-c commented
Done with the mentioned changes

2022-11-25 10:54 UTC, pseudo-rnd-thoughts approved these changes
That policy network figure is very nice, to confirm, this is not copied from someone else and is your own creation.
Also for the top gif, is this from the final agent? The agent doesn't seem to do very well in the environment

2022-11-26 10:37 UTC, siddarth-c commented
The policy learned via REINFORCE is not optimal in Reacher (despite extensive hyperparameter searches).
So I have changed the environment to the Inverted Pendulum, where it is able to learn the optimal policy (achieves max reward of 1000). I hope this change is acceptable.

And yes, the policy network was designed by me

2022-11-26 12:17 UTC, pseudo-rnd-thoughts approved these changes
Amazing, thank you for the tutorial, we would be interested in anymore tutorials that you create

2022-11-26 13:02 UTC, merged