Use SupportsFloat in step_api_compatibility
Farama-Foundation/Gymnasium pull request #368
Opened 2023-03-08 12:54 UTC by software-samurai

The problem is that gym.Env defines step return as Tuple[..., SupportsFloat, ...], and this then can't be passed into functions of `step_api_compatibility`. Alternative to my fix would be to define centrally what is a step return, and reuse the type alias in both places.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-03-08 13:56 UTC, pseudo-rnd-thoughts requested changes
Thanks for fixing that, could you fix the pre-commit issue. See contribution.md for more information

2023-03-09 14:53 UTC, RedTachyon commented
Shouldn't we be starting to deprecate or remove the step api compatibility thing? It makes sense in gym, but technically speaking, Gymnasium never had a different step API

2023-03-09 17:16 UTC, pseudo-rnd-thoughts commented
> Shouldn't we be starting to deprecate or remove the step api compatibility thing? It makes sense in gym, but technically speaking, Gymnasium never had a different step API

Yes, but I think we should remove it when we remove the compatibility wrappers in v0.29

2023-03-14 15:25 UTC, pseudo-rnd-thoughts approved these changes

2023-03-14 15:31 UTC, merged