Fix and Update Basic Usage's page
Farama-Foundation/Gymnasium pull request #41
Opened 2022-10-07 22:57 UTC by vairodp

# Description

Fix the Basic Usage page docs, by updating the code, fixing it, and also fixing the grammar

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-08 23:46 UTC, pseudo-rnd-thoughts commented
Amazing, I will read through all of the changes tomorrow evening. 
Are you going to review any more files for this PR?

2022-10-09 00:03 UTC, vairodp commented
> Amazing, I will read through all of the changes tomorrow evening. Are you going to review any more files for this PR?

Not in this PR, my plan is to do a PR for every "section" of work that I'm doing and I've already done another PR for the tutorial section. 
If you think is a bad idea I can continue my work in this PR

2022-10-10 11:41 UTC, pseudo-rnd-thoughts requested changes
This looks good except for the `gymn` to `gym`

2022-10-10 11:41 UTC, pseudo-rnd-thoughts commented on gymnasium/core.py
> +        class RelativePosition(gymn.ObservationWrapper):
gym

2022-10-10 11:59 UTC, vairodp commented on gymnasium/core.py
> +        class RelativePosition(gymn.ObservationWrapper):
Aahahahah true, fixed

2022-10-10 12:19 UTC, pseudo-rnd-thoughts approved these changes

2022-10-10 12:19 UTC, merged