add `check_environments_match`
Farama-Foundation/Gymnasium pull request #576
Opened 2023-06-29 14:37 UTC by Kallinteris-Andreas

# Description

implements https://github.com/Farama-Foundation/Gymnasium/issues/575

2023-06-29 19:56 UTC, pseudo-rnd-thoughts requested changes
Could you update the mujoco version test to use this function?

2023-06-29 19:56 UTC, pseudo-rnd-thoughts commented on gymnasium/utils/env_tests.py
Rename to `env_match`

2023-06-29 21:43 UTC, Kallinteris-Andreas commented
`test_mujoco_v3` does not check for equality it checks for close "enought", which this function does not support

2023-06-30 10:57 UTC, pseudo-rnd-thoughts commented on gymnasium/utils/env_tests.py
Sorry, I meant the filename rather the function name, I think `check_environments_match` is a good name

2023-07-01 12:36 UTC, pseudo-rnd-thoughts approved these changes
My only worry is that we don't have any testing but I don't imagine this being a popular function

2023-07-01 12:36 UTC, merged