Add jax to numpy, pytorch and tensorflow
Farama-Foundation/Gymnasium pull request #66
Opened 2022-10-20 01:54 UTC by justinDeu

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-29 21:27 UTC, justinDeu commented
Summary of changes and still outstanding updates:
1. everything moved over to `gymnasium`
2. seems that `GenericTestEnv` changed and doesn't work like you originally set it up in `test_tf_wrapper`, remaining tests still need to be updated to use this
3. didn't make changes to `reset()`, think you meant to include `= None` for both parameters?
4. tests still fail for ints and floats because a conversion function doesn't exist for those. I don't remember how we said we would handle those cases

2022-11-16 14:26 UTC, pseudo-rnd-thoughts requested changes
Considering the problem of zero length arrays and python/numpy values, I think we should just always go for the value. 
This is as zero length arrays shouldn't really exist, we raise a warning for environments that use them and we could raise an error if we try to convert them. 
Therefore, could we add a comment in the documentation.

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_numpy.py
> +    def reset(self, **kwargs) -> Union[np.ndarray, Tuple[np.ndarray, Dict[str, Any]]]:
Update to the full `reset(self, seed: int, options: dict[str, Any]) -> tuple[ObsType, Dict[str, Any]]` and remove the "return_info" check

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_tf.py
> +        obs, reward, done, info = self.env.step(jax_action)
Update in the same way as `JaxToNumpy`

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_tf.py
> +    def reset(self, **kwargs) -> Union[tf.Tensor, Tuple[tf.Tensor, dict]]:
Update in the same way as `JaxToNumpy`

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_torch.py
> +    def __init__(self, env: Env, device: Optional[torch.device] = None):
Should the type not be `Optional[Device]` using the definition to provide at the beginning

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_torch.py
> +        obs, reward, done, info = self.env.step(jax_action)
Update like `JaxToNumpy`

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on gymnasium/dev_wrappers/to_torch.py
> +    def reset(self, **kwargs) -> Union[torch.Tensor, Tuple[torch.Tensor, Dict]]:
Update like `JaxToNumpy`

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_np_wrapper.py
> +        return jnp.array([self.t]), self.t, self.t == len(self.returned_rewards), {}
Add `False` for truncation

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_np_wrapper.py
> +    def reset(
Update for new definition

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_np_wrapper.py
> +    [
Add numpy types as well as python types

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_torch_wrapper.py
> +        return jnp.array([self.t]), self.t, self.t == len(self.returned_rewards), {}
Add `False` for truncation

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_torch_wrapper.py
> +    def reset(
Update for new type definition

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_torch_wrapper.py
> +        1.0,
Should either not be pytorch tensors

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/test_torch_wrapper.py
> +    "value", [np.array([1.0, 2.0, 3.0]), jnp.array([1.0, 2.0, 3.0])]
Why is the first array, `np.array` and the second `jnp`?

2022-11-16 14:26 UTC, pseudo-rnd-thoughts commented on tests/dev_wrappers/utils.py
> +def is_same_types(value, expected_type):
Add docstring and return type

2022-12-01 12:37 UTC, closed without merging