add example fo record episode statistics
Farama-Foundation/Gymnasium pull request #673
Opened 2023-08-18 13:55 UTC by jjshoots

### Description

This adds examples for the vector wrappers.

### To-Do:

- [  ] dict_info_to_list.py
- [  ] jax_to_numpy.py
- [  ] jax_to_torch.py
- [  ] numpy_to_torch.py
- [  ] record_episode_statistics.py
- [  ] stateful_observation.py
- [  ] stateful_reward.py
- [  ] vectorize_action.py
- [  ] vectorize_observation.py
- [  ] vectorize_reward.py

2023-08-25 22:56 UTC, pseudo-rnd-thoughts commented
FYI, I have found that the CI will hang if you don't close a vector env, in particular with async that render stuff

2023-08-26 12:22 UTC, jjshoots commented
@pseudo-rnd-thoughts Gotcha, I was trying to figure that out.

2023-09-05 11:04 UTC, pseudo-rnd-thoughts requested changes
Otherwise, looks good

2023-09-05 11:04 UTC, pseudo-rnd-thoughts commented on gymnasium/wrappers/vector/vectorize_observation.py
> +    class _SingleEnv(Env):
Is there a reason why you changed the name? I think the name is better but is there any other reason?

2023-09-05 11:40 UTC, jjshoots commented on gymnasium/wrappers/vector/dict_info_to_list.py
> -        >>> dict_info = {
Initially when reading it it seemed redundant, but now that you mention it, I probably shouldn't have. Going to put it back in.

2023-09-05 11:52 UTC, pseudo-rnd-thoughts commented on gymnasium/wrappers/vector/vectorize_observation.py
> +    class _SingleEnv(Env):
Fair, that makes sense

2023-09-05 11:54 UTC, pseudo-rnd-thoughts approved these changes

2023-09-05 11:54 UTC, merged