Update third_party_environments.md (SuperTuxKart)
Farama-Foundation/Gymnasium pull request #754
Opened 2023-10-24 08:13 UTC by bpiwowar

Adds SuperTuxKart to the third-party environments

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-10-24 11:06 UTC, pseudo-rnd-thoughts requested changes
Thanks for the PR, could you address the comment then we can merge

2023-10-24 11:06 UTC, pseudo-rnd-thoughts commented on docs/environments/third_party_environments.md
> +### [SuperTuxKart](https://github.com/bpiwowar/pystk2-gymnasium)
Could you move this to alphabetical order

2023-10-24 14:21 UTC, bpiwowar commented
Moved to alphabetical order

2023-10-26 09:58 UTC, pseudo-rnd-thoughts approved these changes

2023-10-26 09:59 UTC, merged