`env_checker` to use exact data_equivilance
Farama-Foundation/Gymnasium pull request #953
Opened 2024-03-07 09:23 UTC by Kallinteris-Andreas

# Description

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-07 22:28 UTC, pseudo-rnd-thoughts requested changes
Like @RedTachyon said, there are cases where floating point makes exact a very difficult standard for projects to require. 
I would prefer to reduce the `allclose` `atol` or `rtol` values than change to `allequal`

2024-03-08 05:12 UTC, Kallinteris-Andreas commented
As I previously said, the operations in `check_env` performs operations deterministically, so there is no concern of FP arithmetic ordering errors

2024-03-08 10:12 UTC, RedTachyon commented
Nitpick:

<img width="391" alt="image" src="https://github.com/Farama-Foundation/Gymnasium/assets/19414946/76d7327b-8d9a-4146-a7f1-63bb22ded2d2">

(yes, this uses nan's - although those would also fail approximate equality tests)

2024-03-08 10:17 UTC, RedTachyon commented
Can't we do like a two-tiered check? If they're not `allclose`, then throw an error because that's a big issue (like what happens now). If it is `allclose` but isn't `==`, then raise a warning.

Alternatively, maybe we can just add a switch in `check_env` controlling how strict the equality checks are.

2024-03-08 11:19 UTC, pseudo-rnd-thoughts commented
I agree with @RedTachyon on the two-tier testing

2024-03-08 13:32 UTC, Kallinteris-Andreas commented
I'm sorry, I do not understand the benefit of a two-tier testing System.  All deterministic environments.  Should fail if they cannot pass `allequal` 

note: NaN It is already tested before the determinism checks.

2024-03-11 11:36 UTC, pseudo-rnd-thoughts commented
From my perspective, we can take the `check_env` function in two directions.
The first is a general testing function for most environments that will generally test possible values but not provide a guarantee. To test determinism, we only test the first reset and step values, ignoring any roll out, meaning that in many ways the function is not that strict. 

The second is a comprehensive testing tool that covers everything about the function. 

In my opinion, we should test the essential core elements of the API comprehensively, while the non-essential elements (i.e., determinism) should be more lacks. Particularly for determinism that is very difficult to guarantee for some environment with external simulators, etc and as Gymnasium is a general API we should try to find a middle ground on this.  

Therefore, a two-tier equivalence system could help provide a middle ground to purely alert users if strict equivalence doesn't hold but not failure that would prevent the rest of the testing suite to complete. 

For non-essential items, I don't want the testing to fail and the user disregard the function when later parts of the function would show essential elements actually failing if they continued using it

2024-03-12 18:26 UTC, pseudo-rnd-thoughts requested changes
Could the warning and error messages be a bit different otherwise it could be difficult for users to understand what is happening

2024-03-12 18:26 UTC, pseudo-rnd-thoughts commented on gymnasium/utils/env_checker.py
>                  assert data_equivalence(
Add warning case and remove exact=True in this case

2024-03-12 18:26 UTC, pseudo-rnd-thoughts commented on gymnasium/utils/env_checker.py
> +    assert data_equivalence(term_0, term_0, True), "step terminal is not deterministic."
`exact=True`

2024-03-14 17:12 UTC, pseudo-rnd-thoughts approved these changes

2024-03-14 17:12 UTC, merged